# Generated by Django 5.1.2 on 2024-11-26 08:41

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('register_number', models.IntegerField(null=True, unique=True, verbose_name='Número de registro')),
                ('nif', models.CharField(max_length=10, null=True, unique=True, verbose_name='NIF')),
                ('phone', models.CharField(default='0000000000', max_length=12, null=True, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email de contacto')),
                ('lat', models.CharField(default='', max_length=50, null=True, verbose_name='Lat')),
                ('lon', models.CharField(default='', max_length=50, null=True, verbose_name='Lon')),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Dirección')),
                ('cp', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Postal Code')),
                ('town', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Municipio')),
                ('province', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.BooleanField(default=True, verbose_name='Ver en Dashboard')),
                ('order', models.IntegerField(default=1, verbose_name='Orden')),
                ('operation_time', models.IntegerField(default=20, verbose_name='Tiempo de operación (min)')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de instalación',
                'verbose_name_plural': 'Tipos de instalación',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=90, null=True, verbose_name='Marca')),
                ('model', models.CharField(max_length=90, null=True, verbose_name='Modelo')),
                ('year', models.CharField(max_length=4, null=True, verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Tipo de camión',
                'verbose_name_plural': 'Tipos de camión',
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='Kg', max_length=10, unique=True, verbose_name='Código')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de unidad',
                'verbose_name_plural': 'Tipos de unidades',
            },
        ),
        migrations.CreateModel(
            name='WasteTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Código')),
                ('description', models.CharField(max_length=900, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tratamiento del residuo',
                'verbose_name_plural': 'Tratamientos de los residuos',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Código')),
                ('nima', models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El NIMA debe tener 10 dígitos y comenzar por 38.', regex='38\\d{8}')], verbose_name='NIMA')),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Descripción')),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Dirección')),
                ('town', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ciudad')),
                ('lat', models.CharField(default='', max_length=50, null=True, verbose_name='Lat')),
                ('lon', models.CharField(default='', max_length=50, null=True, verbose_name='Lon')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.company', verbose_name='Empresa gestora')),
                ('company_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities_owner', to='gestion.company', verbose_name='Empresa propietaria')),
            ],
            options={
                'verbose_name': 'Instalación',
                'verbose_name_plural': 'Instalaciones',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_kilometers', models.BigIntegerField(blank=True, null=True, verbose_name='Kilometros al inicio')),
                ('end_kilometers', models.BigIntegerField(blank=True, null=True, verbose_name='Kilometros al finalizar')),
                ('date', models.DateField(default=datetime.datetime(2024, 11, 27, 8, 41, 3, 942912, tzinfo=datetime.timezone.utc), verbose_name='Fecha de la ruta')),
                ('start_time', models.TimeField(blank=True, default=None, null=True, verbose_name='Hora inicio')),
                ('end_time', models.TimeField(blank=True, default=None, null=True, verbose_name='Hora finalizacion')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Código')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.company', verbose_name='Company')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_source', to='gestion.facility', verbose_name='Origen')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_target', to='gestion.facility', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PointRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(verbose_name='Orden')),
                ('ref', models.IntegerField(blank=True, default='0', null=True, verbose_name='Orden')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Peso')),
                ('verified_driver', models.DateTimeField(blank=True, default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
                ('verified_operator', models.DateTimeField(blank=True, default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gestion.facility', verbose_name='Instalación')),
                ('source', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_source', to='gestion.facility', verbose_name='Punto de origen')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='gestion.route', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Punto de ruta',
                'verbose_name_plural': 'Puntos de ruta',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('on_saturday', models.BooleanField(default=False, verbose_name='Disponible en Sábado')),
                ('itv_date', models.DateField(default=datetime.datetime.today, null=True, verbose_name='Fecha de ITV')),
                ('number_plate', models.CharField(max_length=10, verbose_name='Matrícula')),
                ('observations', models.TextField(blank=True, default='', null=True, verbose_name='Observaciones')),
                ('lat', models.CharField(default='', max_length=50, null=True, verbose_name='Lat')),
                ('lon', models.CharField(default='', max_length=50, null=True, verbose_name='Lon')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.company', verbose_name='Empresa')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.trucktype', verbose_name='Tipo de Camión')),
            ],
            options={
                'verbose_name': 'Camión',
                'verbose_name_plural': 'Camiones',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.truck', verbose_name='Camión'),
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.BooleanField(default=False, verbose_name='Alertas')),
                ('dangerous', models.BooleanField(default=False, verbose_name='Peligroso')),
                ('ler', models.BigIntegerField(null=True, verbose_name='LER')),
                ('day_limit', models.FloatField(blank=True, help_text='Límite diario de recogidas por usuario', null=True, verbose_name='Límite diario')),
                ('score', models.FloatField(blank=True, default=-1, null=True, verbose_name='Puntuacion')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('recycle_text', models.TextField(blank=True, help_text='Texto para fomentar la reutilizacion de residuos por parte del ciudadano', null=True, verbose_name='Texto de Reciclaje')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Icono')),
                ('external_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.company', verbose_name='Gestor Externo')),
                ('units', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.unittype', verbose_name='Unidades')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.wastetreatment', verbose_name='Tratemiento')),
            ],
            options={
                'verbose_name': 'Residuo',
                'verbose_name_plural': 'Residuos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WasteInFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toRoute', models.BooleanField(default=True, verbose_name='En ruta')),
                ('code', models.CharField(default='Cont.000', max_length=255, verbose_name='Código')),
                ('filling_degree', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Porcentaje de llenado')),
                ('warning_filling_degree', models.DecimalField(decimal_places=2, default=45.0, max_digits=5, verbose_name='Umbral de aviso')),
                ('alert_filling_degree', models.DecimalField(decimal_places=2, default=80.0, max_digits=5, verbose_name='Umbral de alerta')),
                ('last_modification', models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 26, 8, 41, 3, 938785, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación')),
                ('advise_frec', models.IntegerField(blank=True, default=15, verbose_name='Advise Frecuency')),
                ('emails', models.CharField(blank=True, default='', max_length=900, verbose_name='Emails')),
                ('subject', models.CharField(blank=True, default='', max_length=900, verbose_name='Subject')),
                ('body', models.TextField(blank=True, default='', verbose_name='Body')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste', to='gestion.facility', verbose_name='Instalación')),
                ('waste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='gestion.waste', verbose_name='Residuo')),
            ],
            options={
                'verbose_name': 'Residuos en instalación',
                'ordering': ['waste__code'],
            },
        ),
    ]
