# Generated by Django 5.1.2 on 2024-11-26 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='register_number',
            field=models.IntegerField(default=0, null=True, verbose_name='Número de registro'),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 27, 8, 56, 8, 980806, tzinfo=datetime.timezone.utc), verbose_name='Fecha de la ruta'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 26, 8, 56, 8, 977826, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
    ]
