# Generated by Django 5.1.2 on 2024-11-26 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_company_register_number_alter_route_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='nif',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20, null=True, verbose_name='Teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 27, 8, 57, 51, 81654, tzinfo=datetime.timezone.utc), verbose_name='Fecha de la ruta'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 26, 8, 57, 51, 79216, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
    ]
