# Generated by Django 5.1.2 on 2024-11-26 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_company_nif_alter_company_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ext_code',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='External code'),
        ),
        migrations.AddField(
            model_name='facility',
            name='ext_code',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='External code'),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 27, 9, 8, 31, 913479, tzinfo=datetime.timezone.utc), verbose_name='Fecha de la ruta'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 26, 9, 8, 31, 911224, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
    ]
