# Generated by Django 5.1.2 on 2024-11-26 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_company_ext_code_facility_ext_code_alter_route_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='code',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='nima',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='NIMA'),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 27, 9, 12, 27, 791209, tzinfo=datetime.timezone.utc), verbose_name='Fecha de la ruta'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 26, 9, 12, 27, 788764, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
    ]
