# Generated by Django 5.1.2 on 2024-11-26 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_facility_code_alter_facility_nima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='nima',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='NIMA'),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 27, 9, 13, 45, 212298, tzinfo=datetime.timezone.utc), verbose_name='Fecha de la ruta'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 26, 9, 13, 45, 209938, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
    ]
