# Generated by Django 5.1.2 on 2024-11-29 11:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_truck_ext_code_trucktype_ext_code_alter_route_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de empleado',
                'verbose_name_plural': 'Tipos de Empleados',
            },
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 30, 11, 23, 20, 202446, tzinfo=datetime.timezone.utc), verbose_name='Fecha de la ruta'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 29, 11, 23, 20, 158582, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Activo')),
                ('code', models.CharField(max_length=10, null=True, unique=True, verbose_name='Código de Empleado')),
                ('nif', models.CharField(max_length=10, null=True, unique=True, verbose_name='NIF')),
                ('pin', models.CharField(max_length=10, null=True, unique=True, verbose_name='PIN')),
                ('device_uid', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='DeviceUID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('cellphone', models.CharField(default='0000000000', max_length=10, null=True, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email de contacto')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='gestion.company', verbose_name='Empresa')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='gestion.facility', verbose_name='Instalación')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['code', 'name'],
            },
        ),
    ]
