# Generated by Django 5.1.2 on 2024-11-29 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_employee_device_uid_alter_route_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 30, 11, 46, 0, 692961, tzinfo=datetime.timezone.utc), verbose_name='Fecha de la ruta'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 29, 11, 46, 0, 646534, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
    ]
