# Generated by Django 5.1.2 on 2024-11-29 12:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_route_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.employeetype', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 30, 12, 27, 44, 577293, tzinfo=datetime.timezone.utc), verbose_name='Fecha de la ruta'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 29, 12, 27, 44, 548269, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
    ]
