# Generated by Django 5.1.2 on 2024-12-02 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_employee_rol_alter_route_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetype',
            name='code',
            field=models.CharField(max_length=10, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 3, 9, 40, 29, 540154, tzinfo=datetime.timezone.utc), verbose_name='Fecha de la ruta'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 2, 9, 40, 29, 501502, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
    ]
