# Generated by Django 5.1.2 on 2024-12-05 11:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_employeetype_code_alter_route_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 11, 4, 23, 81202, tzinfo=datetime.timezone.utc), verbose_name='Fecha de la ruta'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 5, 11, 4, 23, 32564, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
        migrations.CreateModel(
            name='EmployeeTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Fecha de ITV')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='gestion.employee', verbose_name='Empleado')),
                ('truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='gestion.truck', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Empleado Camion',
                'verbose_name_plural': 'Empleados Camiones',
            },
        ),
    ]
