# Generated by Django 5.1.2 on 2024-12-12 09:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_route_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-ini_date'], 'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.RemoveField(
            model_name='route',
            name='company',
        ),
        migrations.RemoveField(
            model_name='route',
            name='date',
        ),
        migrations.RemoveField(
            model_name='route',
            name='end_kilometers',
        ),
        migrations.RemoveField(
            model_name='route',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_kilometers',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_time',
        ),
        migrations.AddField(
            model_name='route',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.employee', verbose_name='Conductor'),
        ),
        migrations.AddField(
            model_name='route',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Fin'),
        ),
        migrations.AddField(
            model_name='route',
            name='finish',
            field=models.BooleanField(default=False, verbose_name='Finalizada'),
        ),
        migrations.AddField(
            model_name='route',
            name='ini_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Inicio'),
        ),
        migrations.AddField(
            model_name='route',
            name='waste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.waste', verbose_name='Residuo'),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_source', to='gestion.facility', verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='route',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_target', to='gestion.facility', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='route',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.truck', verbose_name='Camión'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 12, 9, 45, 15, 724139, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
        migrations.DeleteModel(
            name='PointRoute',
        ),
    ]
