# Generated by Django 5.1.2 on 2024-12-12 09:47

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_alter_route_options_remove_route_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='route',
            name='ini_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 12, 9, 47, 15, 609956, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
    ]
