# Generated by Django 5.1.2 on 2024-12-12 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_route_end_date_alter_route_ini_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='ext_code',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='External code'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 12, 11, 13, 51, 212506, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
    ]
