# Generated by Django 5.1.2 on 2024-12-13 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_waste_ext_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='code',
            field=models.CharField(max_length=8, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 13, 9, 28, 29, 963412, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
    ]
