# Generated by Django 5.1.2 on 2025-01-07 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_alter_route_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteinfacility',
            name='ext_code',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='External code'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 7, 21, 58, 26, 750999, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
    ]
