# Generated by Django 5.1.2 on 2025-01-08 12:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_wasteinfacility_ext_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='base_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.facility', verbose_name='Estación Base'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 8, 12, 11, 34, 209627, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
    ]
