# Generated by Django 5.1.2 on 2025-01-08 13:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_truck_base_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteinfacility',
            name='alt_download_point',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_alt', to='gestion.facility', verbose_name='Descarga alternativo'),
        ),
        migrations.AddField(
            model_name='wasteinfacility',
            name='download_point',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download', to='gestion.facility', verbose_name='Punto de descarga'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 8, 13, 2, 40, 467057, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
    ]
