# Generated by Django 5.1.2 on 2025-01-08 13:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_wasteinfacility_alt_download_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='waste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.wasteinfacility', verbose_name='Residuo'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 8, 13, 14, 28, 884575, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
    ]
