# Generated by Django 5.1.2 on 2025-01-08 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_alter_route_waste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 8, 13, 40, 31, 413715, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
    ]
