# Generated by Django 5.1.2 on 2025-01-13 09:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_route_weight_alter_wasteinfacility_last_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 13, 9, 50, 54, 863844, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
        migrations.CreateModel(
            name='EmployeeAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.BooleanField(default=False, verbose_name='Finalizada')),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Fecha de acceso')),
                ('location', models.TextField(default='', null=True, verbose_name='Fecha de acceso')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access', to='gestion.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Acceso de Empleado',
                'verbose_name_plural': 'Acceso de Empleados',
            },
        ),
    ]
