# Generated by Django 5.1.2 on 2025-01-15 11:54

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_alter_wasteinfacility_last_modification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 15, 11, 54, 49, 782313, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
        migrations.CreateModel(
            name='RouteMpl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.BooleanField(default=False, verbose_name='Finalizada')),
                ('code', models.CharField(max_length=8, verbose_name='Código')),
                ('ini_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Inicio')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fin')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.employee', verbose_name='Conductor')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_mpl_target', to='gestion.facility', verbose_name='Destino')),
                ('truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.truck', verbose_name='Camión')),
            ],
            options={
                'verbose_name': 'Ruta MPL',
                'verbose_name_plural': 'Rutas MPL',
                'ordering': ['-ini_date'],
            },
        ),
        migrations.CreateModel(
            name='RouteMplPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0, verbose_name='Peso')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fecha')),
                ('mpl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_mpl', to='gestion.facility', verbose_name='Origen')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.routempl', verbose_name='Ruta')),
                ('waste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.wasteinfacility', verbose_name='Residuo')),
            ],
            options={
                'verbose_name': 'Punto de Ruta MPL',
                'verbose_name_plural': 'Puntos de Rutas MPL',
                'ordering': ['-date'],
            },
        ),
    ]
