# Generated by Django 5.1.2 on 2025-01-16 14:08

import datetime
import django.db.models.deletion
import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_alter_wasteinfacility_last_modification_routempl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, help_text='Select file to upload', upload_to=gestion.models.upload_route_image, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='routemplpoint',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='gestion.routempl', verbose_name='Ruta'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 16, 14, 8, 58, 935466, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
    ]
