# Generated by Django 5.1.2 on 2025-01-20 13:52

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_route_image_alter_routemplpoint_route_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Otra acción',
                'verbose_name_plural': 'Otras acciones',
            },
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 20, 13, 52, 14, 370125, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
        migrations.CreateModel(
            name='FacilityActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Inicio')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.employee', verbose_name='Conductor')),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='gestion.facility', verbose_name='Origen')),
                ('truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.truck', verbose_name='Camión')),
                ('fa_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.facilityactiontype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Otra acción',
                'verbose_name_plural': 'Otras acciones',
                'ordering': ['-date'],
            },
        ),
    ]
