# Generated by Django 5.1.2 on 2025-01-21 09:53

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_facilityactiontype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Bandeja',
                'verbose_name_plural': 'Bandejas',
            },
        ),
        migrations.AlterModelOptions(
            name='facilityactions',
            options={'ordering': ['-date'], 'verbose_name': 'Otra acción conductor', 'verbose_name_plural': 'Otras acciones conductores'},
        ),
        migrations.AlterField(
            model_name='facilityactions',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='gestion.employee', verbose_name='Conductor'),
        ),
        migrations.AlterField(
            model_name='wasteinfacility',
            name='last_modification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 21, 9, 53, 34, 454161, tzinfo=datetime.timezone.utc), null=True, verbose_name='Última modificación'),
        ),
        migrations.CreateModel(
            name='TrayTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.BooleanField(default=False, verbose_name='Finalizada')),
                ('ini_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Inicio')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fin')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.employee', verbose_name='Conductor')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trays_source', to='gestion.facility', verbose_name='Origen')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trays_target', to='gestion.facility', verbose_name='Destino')),
                ('tray', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='gestion.tray', verbose_name='Bandeja')),
                ('truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.truck', verbose_name='Camión')),
            ],
            options={
                'verbose_name': 'Localización Bandeja',
                'verbose_name_plural': 'Localización Bandejas',
            },
        ),
    ]
