# Generated by Django 5.1.2 on 2025-01-28 13:20

import citizens.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0036_alter_wasteinfacility_last_modification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Isla')),
            ],
            options={
                'verbose_name': 'Isla',
                'verbose_name_plural': 'Islas',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Municipio')),
                ('island', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizens.island', verbose_name='Isla')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=citizens.models.get_next_code, max_length=6, null=True, verbose_name='Código')),
                ('device', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dispositivo')),
                ('identification', models.CharField(blank=True, default='', max_length=200, verbose_name='Idenitificación')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Domicilio Social')),
                ('plate', models.CharField(blank=True, max_length=255, verbose_name='Matrícula')),
                ('phone', models.CharField(blank=True, default='000000000', max_length=12, null=True, verbose_name='Teléfono')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('employment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizens', to='gestion.employee', verbose_name='Operario')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizens', to='gestion.facility', verbose_name='Instalación')),
                ('town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizens.town', verbose_name='Término municipal')),
            ],
            options={
                'verbose_name': 'Ciudadano',
                'verbose_name_plural': 'Ciudadano',
            },
        ),
    ]
