# Generated by Django 5.1.2 on 2025-01-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='employment',
            new_name='employee',
        ),
    ]
