# Generated by Django 3.2.15 on 2025-02-12 13:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ini_date', models.DateField(default=datetime.datetime.today, verbose_name='ini date')),
                ('end_date', models.DateField(default=datetime.datetime.today, verbose_name='end date')),
                ('ini_time', models.TimeField(default=datetime.datetime.now, verbose_name='ini hour')),
                ('end_time', models.TimeField(default=datetime.datetime.now, verbose_name='end hour')),
                ('name', models.CharField(blank=True, default='', max_length=600, verbose_name='Nombre')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('employees', models.ManyToManyField(blank=True, related_name='user_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Empleados')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-ini_date'],
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.BooleanField(default=False, verbose_name='Cerrada')),
                ('ini_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='ini date')),
                ('end_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='end date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Jornada laboral',
                'verbose_name_plural': 'Jornadas laborales',
                'ordering': ['-ini_date'],
            },
        ),
    ]
