# Generated by Django 5.1.2 on 2025-01-22 11:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Código')),
                ('operator', models.BooleanField(default=False, verbose_name='Operario')),
                ('driver', models.BooleanField(default=False, verbose_name='Conductor')),
            ],
            options={
                'verbose_name': 'Tipo de Incidente',
                'verbose_name_plural': 'Tipos de Incidentes',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed', models.BooleanField(default=False, verbose_name='Estado')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('subject', models.CharField(max_length=255, verbose_name='Asunto')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Descripción')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2025, 1, 22, 11, 47, 21, 897792, tzinfo=datetime.timezone.utc), verbose_name='Creado el')),
                ('closed_date', models.DateTimeField(blank=True, default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999), null=True, verbose_name='Cerrado el')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='incidents.incidenttype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-creation_date'],
            },
        ),
    ]
